# Generated by Django 5.2.4 on 2025-08-07 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=600, verbose_name='description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('FINISHED', 'Finished'), ('CLOSED', 'Closed')], default='OPEN')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ('-created_at',),
                'permissions': [('can_change_status_only', 'Can only edit status of the ticket. reserved For Technitians'), ('can_change_title_desc_only', 'Can only edit the title and description. For regular employe'), ('can_assign_technician', 'Can chose who is in charge of the ticket. For the admin only')],
            },
        ),
    ]
